---
- name: Add PyPy PPA repository
  become: true
  apt_repository: repo=ppa:pypy/ppa state=present
  when: python_dev_install_pypy
- name: Install PyPy
  apt:
    name:
      - pypy
      - pypy-dev
      - python-cffi
    state: latest
  become: true
  when: python_dev_install_pypy